name: Build

env:
  MOD_NAME: ExampleUI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: |
        ./build.ps1 -Release

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: ULTRAINTERFACE.nupkg
        path: ./ULTRAINTERFACE/Package/ULTRAINTERFACE.nupkg
        if-no-files-found: error

        
    - name: Upload Example Mod
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.MOD_NAME }}.dll
        path: ./ExampleUI/bin/Release/net471/win-x64/publish/${{ env.MOD_NAME }}.dll
        if-no-files-found: error